project:
  type: book

book:
  title: "Best Practices for Spatial Transcriptomics Analysis with Bioconductor"
  date: today
  sidebar:
    title: "Best Practices ST"
    style: docked
  search: true
  repo-url: https://github.com/lmweber/BestPracticesST
  cover-image: Bioconductor-rh.png
  chapters:
    - index.qmd
    - part: "Introduction"
      chapters:
        - chapters/introduction.qmd

number-sections: true

bibliography: references.bib

execute:
  freeze: auto

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
